version: '3'
services:
  postgres:
    image: postgres:10.3-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/home:/home
    ports:
      - 5432:5432
    env_file:
      - ./postgres/.env
    networks:
      - addons
  redis:
    image: redis:4.0-alpine
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    networks:
      - redis
      - addons
  redsmin-proxy:
    image: redsmin/proxy:latest
    env_file:
      - ./redsmin-proxy/.env
    networks:
      - redis
      - addons
  rabbitmq:
    image: rabbitmq:3.7-alpine
    ports:
      - 5672:5672
    networks:
      - addons
  aws-cli:
    image: mesosphere/aws-cli:latest
    env_file:
      - ./aws-cli/.env
    networks:
      - addons
networks:
  redis:
  addons:
    external: true
